/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as TransportadoraRouteImport } from './routes/transportadora'
import { Route as RastreamentoRouteImport } from './routes/rastreamento'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViagensIndexRouteImport } from './routes/viagens.index'
import { Route as MotoristaIndexRouteImport } from './routes/motorista.index'
import { Route as ViagensIdRouteImport } from './routes/viagens.$id'
import { Route as MotoristaViagensRouteImport } from './routes/motorista.viagens'
import { Route as MotoristaDashboardRouteImport } from './routes/motorista.dashboard'
import { Route as MotoristaViagensIndexRouteImport } from './routes/motorista.viagens.index'
import { Route as MotoristaViagensIdRouteImport } from './routes/motorista.viagens.$id'

const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportadoraRoute = TransportadoraRouteImport.update({
  id: '/transportadora',
  path: '/transportadora',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreamentoRoute = RastreamentoRouteImport.update({
  id: '/rastreamento',
  path: '/rastreamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensIndexRoute = ViagensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViagensRoute,
} as any)
const MotoristaIndexRoute = MotoristaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MotoristaRoute,
} as any)
const ViagensIdRoute = ViagensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ViagensRoute,
} as any)
const MotoristaViagensRoute = MotoristaViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaDashboardRoute = MotoristaDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaViagensIndexRoute = MotoristaViagensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MotoristaViagensRoute,
} as any)
const MotoristaViagensIdRoute = MotoristaViagensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MotoristaViagensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRouteWithChildren
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/rastreamento': typeof RastreamentoRoute
  '/transportadora': typeof TransportadoraRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRouteWithChildren
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/motorista/viagens': typeof MotoristaViagensRouteWithChildren
  '/viagens/$id': typeof ViagensIdRoute
  '/motorista/': typeof MotoristaIndexRoute
  '/viagens/': typeof ViagensIndexRoute
  '/motorista/viagens/$id': typeof MotoristaViagensIdRoute
  '/motorista/viagens/': typeof MotoristaViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/rastreamento': typeof RastreamentoRoute
  '/transportadora': typeof TransportadoraRoute
  '/veiculos': typeof VeiculosRoute
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/viagens/$id': typeof ViagensIdRoute
  '/motorista': typeof MotoristaIndexRoute
  '/viagens': typeof ViagensIndexRoute
  '/motorista/viagens/$id': typeof MotoristaViagensIdRoute
  '/motorista/viagens': typeof MotoristaViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRouteWithChildren
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/rastreamento': typeof RastreamentoRoute
  '/transportadora': typeof TransportadoraRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRouteWithChildren
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/motorista/viagens': typeof MotoristaViagensRouteWithChildren
  '/viagens/$id': typeof ViagensIdRoute
  '/motorista/': typeof MotoristaIndexRoute
  '/viagens/': typeof ViagensIndexRoute
  '/motorista/viagens/$id': typeof MotoristaViagensIdRoute
  '/motorista/viagens/': typeof MotoristaViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/login'
    | '/motorista'
    | '/motoristas'
    | '/produtos'
    | '/rastreamento'
    | '/transportadora'
    | '/veiculos'
    | '/viagens'
    | '/motorista/dashboard'
    | '/motorista/viagens'
    | '/viagens/$id'
    | '/motorista/'
    | '/viagens/'
    | '/motorista/viagens/$id'
    | '/motorista/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/login'
    | '/motoristas'
    | '/produtos'
    | '/rastreamento'
    | '/transportadora'
    | '/veiculos'
    | '/motorista/dashboard'
    | '/viagens/$id'
    | '/motorista'
    | '/viagens'
    | '/motorista/viagens/$id'
    | '/motorista/viagens'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/login'
    | '/motorista'
    | '/motoristas'
    | '/produtos'
    | '/rastreamento'
    | '/transportadora'
    | '/veiculos'
    | '/viagens'
    | '/motorista/dashboard'
    | '/motorista/viagens'
    | '/viagens/$id'
    | '/motorista/'
    | '/viagens/'
    | '/motorista/viagens/$id'
    | '/motorista/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  LoginRoute: typeof LoginRoute
  MotoristaRoute: typeof MotoristaRouteWithChildren
  MotoristasRoute: typeof MotoristasRoute
  ProdutosRoute: typeof ProdutosRoute
  RastreamentoRoute: typeof RastreamentoRoute
  TransportadoraRoute: typeof TransportadoraRoute
  VeiculosRoute: typeof VeiculosRoute
  ViagensRoute: typeof ViagensRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportadora': {
      id: '/transportadora'
      path: '/transportadora'
      fullPath: '/transportadora'
      preLoaderRoute: typeof TransportadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreamento': {
      id: '/rastreamento'
      path: '/rastreamento'
      fullPath: '/rastreamento'
      preLoaderRoute: typeof RastreamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/': {
      id: '/viagens/'
      path: '/'
      fullPath: '/viagens/'
      preLoaderRoute: typeof ViagensIndexRouteImport
      parentRoute: typeof ViagensRoute
    }
    '/motorista/': {
      id: '/motorista/'
      path: '/'
      fullPath: '/motorista/'
      preLoaderRoute: typeof MotoristaIndexRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/viagens/$id': {
      id: '/viagens/$id'
      path: '/$id'
      fullPath: '/viagens/$id'
      preLoaderRoute: typeof ViagensIdRouteImport
      parentRoute: typeof ViagensRoute
    }
    '/motorista/viagens': {
      id: '/motorista/viagens'
      path: '/viagens'
      fullPath: '/motorista/viagens'
      preLoaderRoute: typeof MotoristaViagensRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/dashboard': {
      id: '/motorista/dashboard'
      path: '/dashboard'
      fullPath: '/motorista/dashboard'
      preLoaderRoute: typeof MotoristaDashboardRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/viagens/': {
      id: '/motorista/viagens/'
      path: '/'
      fullPath: '/motorista/viagens/'
      preLoaderRoute: typeof MotoristaViagensIndexRouteImport
      parentRoute: typeof MotoristaViagensRoute
    }
    '/motorista/viagens/$id': {
      id: '/motorista/viagens/$id'
      path: '/$id'
      fullPath: '/motorista/viagens/$id'
      preLoaderRoute: typeof MotoristaViagensIdRouteImport
      parentRoute: typeof MotoristaViagensRoute
    }
  }
}

interface MotoristaViagensRouteChildren {
  MotoristaViagensIdRoute: typeof MotoristaViagensIdRoute
  MotoristaViagensIndexRoute: typeof MotoristaViagensIndexRoute
}

const MotoristaViagensRouteChildren: MotoristaViagensRouteChildren = {
  MotoristaViagensIdRoute: MotoristaViagensIdRoute,
  MotoristaViagensIndexRoute: MotoristaViagensIndexRoute,
}

const MotoristaViagensRouteWithChildren =
  MotoristaViagensRoute._addFileChildren(MotoristaViagensRouteChildren)

interface MotoristaRouteChildren {
  MotoristaDashboardRoute: typeof MotoristaDashboardRoute
  MotoristaViagensRoute: typeof MotoristaViagensRouteWithChildren
  MotoristaIndexRoute: typeof MotoristaIndexRoute
}

const MotoristaRouteChildren: MotoristaRouteChildren = {
  MotoristaDashboardRoute: MotoristaDashboardRoute,
  MotoristaViagensRoute: MotoristaViagensRouteWithChildren,
  MotoristaIndexRoute: MotoristaIndexRoute,
}

const MotoristaRouteWithChildren = MotoristaRoute._addFileChildren(
  MotoristaRouteChildren,
)

interface ViagensRouteChildren {
  ViagensIdRoute: typeof ViagensIdRoute
  ViagensIndexRoute: typeof ViagensIndexRoute
}

const ViagensRouteChildren: ViagensRouteChildren = {
  ViagensIdRoute: ViagensIdRoute,
  ViagensIndexRoute: ViagensIndexRoute,
}

const ViagensRouteWithChildren =
  ViagensRoute._addFileChildren(ViagensRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  LoginRoute: LoginRoute,
  MotoristaRoute: MotoristaRouteWithChildren,
  MotoristasRoute: MotoristasRoute,
  ProdutosRoute: ProdutosRoute,
  RastreamentoRoute: RastreamentoRoute,
  TransportadoraRoute: TransportadoraRoute,
  VeiculosRoute: VeiculosRoute,
  ViagensRoute: ViagensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
