/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as TransportadoraRouteImport } from './routes/transportadora'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViagensIdRouteImport } from './routes/viagens.$id'

const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportadoraRoute = TransportadoraRouteImport.update({
  id: '/transportadora',
  path: '/transportadora',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensIdRoute = ViagensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ViagensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/transportadora': typeof TransportadoraRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRouteWithChildren
  '/viagens/$id': typeof ViagensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/transportadora': typeof TransportadoraRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRouteWithChildren
  '/viagens/$id': typeof ViagensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/transportadora': typeof TransportadoraRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRouteWithChildren
  '/viagens/$id': typeof ViagensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/motoristas'
    | '/produtos'
    | '/transportadora'
    | '/veiculos'
    | '/viagens'
    | '/viagens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/motoristas'
    | '/produtos'
    | '/transportadora'
    | '/veiculos'
    | '/viagens'
    | '/viagens/$id'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/motoristas'
    | '/produtos'
    | '/transportadora'
    | '/veiculos'
    | '/viagens'
    | '/viagens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  MotoristasRoute: typeof MotoristasRoute
  ProdutosRoute: typeof ProdutosRoute
  TransportadoraRoute: typeof TransportadoraRoute
  VeiculosRoute: typeof VeiculosRoute
  ViagensRoute: typeof ViagensRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportadora': {
      id: '/transportadora'
      path: '/transportadora'
      fullPath: '/transportadora'
      preLoaderRoute: typeof TransportadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/$id': {
      id: '/viagens/$id'
      path: '/$id'
      fullPath: '/viagens/$id'
      preLoaderRoute: typeof ViagensIdRouteImport
      parentRoute: typeof ViagensRoute
    }
  }
}

interface ViagensRouteChildren {
  ViagensIdRoute: typeof ViagensIdRoute
}

const ViagensRouteChildren: ViagensRouteChildren = {
  ViagensIdRoute: ViagensIdRoute,
}

const ViagensRouteWithChildren =
  ViagensRoute._addFileChildren(ViagensRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  MotoristasRoute: MotoristasRoute,
  ProdutosRoute: ProdutosRoute,
  TransportadoraRoute: TransportadoraRoute,
  VeiculosRoute: VeiculosRoute,
  ViagensRoute: ViagensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
